### ISSUE TITLE
Exception getting optionset metadata info from Dataverse : Failed to resolve....

### ISSUE THREAD

**Issue by Gareth064** [microsoft/PowerPlatform-DataverseServiceClient#364] opened 2023-03-20 09:31 UTC
We have a system integrations using function apps, which when triggered, read data from the Dataverse, and sync it to another systems.

One particular function app runs 50k-60k times a day. It could fail a few times a day due to not being able to get something from the dataverse, which it can easily get thousands of other times.

The error below reads to me that something was not quite right on the Dataverse side. Is there anything I can do/check in the Dataverse to figure out why it was closing the connection?

The errors come in 3 for the same function app integration instance.
```
************ CommunicationException - RetrieveOptionSet : GetGlobalOptionSetMetadata |=> An error occurred while sending the request.

Source: System.Private.ServiceModel
Method: ProcessGetResponseWebException
DateUTC: 3/19/2023 TimeUTC: 1:35:40 AM
Error: An error occurred while sending the request.
HelpLink Url: Not Provided

Stack Trace: at System.ServiceModel.Channels.HttpChannelUtilities.ProcessGetResponseWebException(HttpRequestException requestException, HttpRequestMessage request, HttpAbortReason abortReason)
at System.ServiceModel.Channels.HttpChannelFactory`1.HttpClientRequestChannel.HttpClientChannelAsyncRequest.SendRequestAsync(Message message, TimeoutHelper timeoutHelper)
at System.ServiceModel.Channels.RequestChannel.RequestAsync(Message message, TimeSpan timeout)
at System.ServiceModel.Channels.RequestChannel.RequestAsyncInternal(Message message, TimeSpan timeout)
at System.Runtime.TaskHelpers.WaitForCompletionNoSpin[TResult](Task`1 task)
at System.ServiceModel.Channels.RequestChannel.Request(Message message, TimeSpan timeout)
at System.ServiceModel.Dispatcher.RequestChannelBinder.Request(Message message, TimeSpan timeout)
at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout) at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(MethodCall methodCall, ProxyOperationRuntime operation)
at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(MethodInfo targetMethod, Object[] args)
at generatedProxy_1.Execute(OrganizationRequest )
at Microsoft.PowerPlatform.Dataverse.Client.Connector.OrganizationWebProxyClientAsync.<>c__DisplayClass52_0.b__0()
at Microsoft.PowerPlatform.Dataverse.Client.Connector.WebProxyClientAsync`1.ExecuteAction[TResult](Func`1 action)
at Microsoft.PowerPlatform.Dataverse.Client.Connector.OrganizationWebProxyClientAsync.ExecuteCore(OrganizationRequest request)
at Microsoft.PowerPlatform.Dataverse.Client.Connector.OrganizationWebProxyClientAsync.Execute(OrganizationRequest request)
at Microsoft.PowerPlatform.Dataverse.Client.ServiceClient.Command_Execute(OrganizationRequest req, String errorStringCheck, Boolean bypassPluginExecution)
======================================================================================================================
Inner Exception Level 1 :
Source: System.Net.Http
Method: MoveNext
DateUTC: 3/19/2023
TimeUTC: 1:35:40 AM
Error: An error occurred while sending the request.
HelpLink Url: Not Provided

Stack Trace: at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
at System.Net.Http.HttpClient.g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
at System.ServiceModel.Channels.HttpChannelFactory`1.HttpClientRequestChannel.HttpClientChannelAsyncRequest.SendRequestAsync(Message message, TimeoutHelper timeoutHelper)
======================================================================================================================
Inner Exception Level 2 :
Source: System.Net.Sockets
Method: ThrowException
DateUTC: 3/19/2023 TimeUTC: 1:35:40 AM
Error: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host..
HelpLink Url: Not Provided

Stack Trace: at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer) at System.Net.Http.HttpConnection.g__ReadAheadWithZeroByteReadAsync|45_0()
at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
======================================================================================================================
Inner Exception Level 3 :
Source: Not Provided
Method: Not Provided
DateUTC: 3/19/2023 TimeUTC: 1:35:40 AM
Error: An existing connection was forcibly closed by the remote host.
HelpLink Url: Not Provided

Stack Trace: Not Provided
======================================================================================================================
```

```
[TerminalFailure] Failed to Execute Command - RetrieveOptionSet : RequestID=f8beed67-ca9f-4256-8da7-81aefa2190a7 : GetGlobalOptionSetMetadata duration=00:00:18.9689877 ExceptionMessage = An error occurred while sending the request.
```

```
************ Exception getting optionset metadata info from Dataverse : Failed to resolve global optionset metadata for msdyn_wosystemstatus.
Source: Not Provided
Method: Not Provided
DateUTC: 3/19/2023 TimeUTC: 1:35:40 AM
Error: ************ Exception getting optionset metadata info from Dataverse : Failed to resolve global optionset metadata for msdyn_wosystemstatus.
HelpLink Url: Not Provided
Stack Trace: Not Provided ======================================================================================================================
```

**Comment by Gareth064** [comment] 2023-03-20 09:37
Further context.

The integration works like so

- Logic App triggers on changes to data in Dataverse
- Logic app sends request to Function App to start the integration process.
- If the Function App throws an error back to the Logic App, the Logic app starts a retry mechanism.

So in these instances, the integration run is retried and works the second time.

My problem is we are using app insights, and to me it feels like we are logging Exceptions (from the function app) that we don't really need to because the logic app retries eventually and the integration is successful.

So either:
- Figure out this issue to stop it completely, so it isn't logging exceptions that we don't need to look into.
- Or move the retry mechanism into the function app and ONLY log the exception if all retries fail.

**Comment by MattB-msft** [comment] 2023-03-22 16:33
First off: 
"An existing connection was forcibly closed by the remote host." is a networking layer failure. 
Its generally caused by a network in the middle terminating the connection, if this is happening frequently, I would suspect a misconfigured gateway or firewall. 
The ServiceClient does not auto retry these as (historically) they tend to be terminal, and no amount of retry within the few milliseconds will resolve it.  That said, the changes made to the .net 6 + networking stack seem to have caused these issues to appear more frequently when mixed with some firewall / packet filtering solutions.   Depending on how frequently it surfaces in the future, we may provide a retry option (enabled on request) to retry them internally to the client.   We have been discussing that internally. 

on the second concern. 
You could use a [telemetry ](https://learn.microsoft.com/en-us/azure/azure-monitor/app/api-filtering-sampling#filtering) processor to skip these exceptions to AppInsights..

**Comment by MattB-msft** [comment] 2023-04-06 16:34
Closing this at this point, 
If there is a follow up, please reopen with more information. 

thanks!

**Closed by MattB-msft** 2023-04-06 16:34 UTC
