### ISSUE TITLE
OAuth CRM Connection causing issue with CommitFileBlocksUploadRequest()

### ISSUE THREAD

**Issue by krishire** [microsoft/PowerPlatform-DataverseServiceClient#145] opened 2021-07-13 15:24 UTC
Hi,
Please help me with this issue, I'm getting the following error, when I make a CommitFileBlocksUploadRequest() Request.
The same request works with the CRM Service (Office365) Connection, but failign with 0Auth Connection.

System.InvalidOperationException: Identity of caller can not be found in HttpContext.
   at Microsoft.Xrm.Kernel.Runtime.UserIdValidator.Validate(Guid userId, Boolean isInClientContext) +0x26
   at Microsoft.Crm.Extensibility.PipelineExecutionContext.get_InitiatingUserId() +0x2b
   at

**Comment by MattB-msft** [comment] 2021-07-15 17:27
Can you provide an example of your code use? 
I am forwarding this onto our API team to have a look.  also did you open a support ticket on this?

**Comment by krishire** [comment] 2021-07-15 18:07
Yes Matt, I have raised a ticket with Microsoft, they are looking into it.
Tomorrow when I login back in office, will give you the ticket number that
has the full code I used, crm environment etc. Many thanks for your help.

Thanks,
Krish.

**Comment by krishire** [comment] 2021-07-16 14:07
Hi Matt, Sorry for the delay.
Microsoft TrackingID #210713005000267

Connection string used:
AuthType=OAuth;Username=***@Sample.com;Password=**********;Url=https://*******.crm11.dynamics.com/;AppId=*************;RedirectUri=https://**********************/; LoginPrompt=Auto

Here is the code:
try
            {  

                var connectionString = string.Format("AuthType={0};Username={1};Password={2};Url={3};AppId={4};RedirectUri={5}; LoginPrompt=Auto", ConfigurationManager.AppSettings["AuthType"],
                    ConfigurationManager.AppSettings["CRMUserId"], DataProtect.DecryptString(ConfigurationManager.AppSettings["CRMUserPassword"]), ConfigurationManager.AppSettings["Organizationurl"],
                    ConfigurationManager.AppSettings["AppId"], ConfigurationManager.AppSettings["RedirectUri"]
                    );

                ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;

                var service = new Microsoft.Xrm.Tooling.Connector.CrmServiceClient(connectionString);

                if (!service.IsReady)
                {
                    throw new Exception("Could not connect to CRM. " + connectionString + " " + service.LastCrmException);
                }
                else
                {
                    Trace.WriteLine(DateTime.Now.ToString(CultureInfo.InvariantCulture) + ":CRM Connection established!");

                    byte[] bytes = Encoding.ASCII.GetBytes(jsonString);
                    var importDataFile = new Entity("<entityid>");
                    importDataFile["rbs_name"] = "Test Microsoft Mansi-" + DateTime.Now; 
                    var recGuid = service.Create(importDataFile);

                    string fileName = "Test_" + DateTime.Now.ToLongDateString() + ".json";

                    var initRequest = new InitializeFileBlocksUploadRequest()
                    {
                        FileAttributeName = "rbs_file",
                        FileName = fileName,
                        Target = new EntityReference("rbs_edbdataimportfile", recGuid)
                    };
                    var initResponse = (InitializeFileBlocksUploadResponse)service.Execute(initRequest);

                    var limit = 4194304;
                    var fileContinuationToken = initResponse.FileContinuationToken;
                    var blockIds = new List<string>();


                    for (int i = 0; i < Math.Ceiling(bytes.Length / Convert.ToDecimal(limit)); i++)
                    {
                        var blockId = Convert.ToBase64String(Encoding.UTF8.GetBytes(Guid.NewGuid().ToString()));
                        blockIds.Add(blockId);
                        var blockData = bytes.Skip(i * limit).Take(limit).ToArray();
                        var blockRequest = new UploadBlockRequest() { FileContinuationToken = fileContinuationToken, BlockId = blockId, BlockData = blockData };
                        var blockResponse = (UploadBlockResponse)service.Execute(blockRequest);
                    }

                    var commitRequest = new CommitFileBlocksUploadRequest()
                    {
                        BlockList = blockIds.ToArray(),
                        FileContinuationToken = fileContinuationToken,
                        FileName = fileName,
                        MimeType = @"application/json"
                    };

                    service.Execute(commitRequest);  //Fails in this line.

                    Trace.WriteLine(DateTime.Now.ToString(CultureInfo.InvariantCulture) + ":CRM Data Import File Record(" + fileName + ") Created and Updated with File & Ready to Process Status");

                }
            }
            catch (Exception exp)
            {
                Trace.WriteLine(DateTime.Now.ToString(CultureInfo.InvariantCulture) + $":CreateCRMImportRecord Method Exception: { exp.Message };StactTrace: {exp.StackTrace}");
                throw;
            }

Server stack trace: 
   at System.ServiceModel.Channels.ServiceChannel.HandleReply(ProxyOperationRuntime operation, ProxyRpc& rpc)
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at Microsoft.Xrm.Tooling.Connector.CrmServiceClient.Execute(OrganizationRequest request)
   at NWG.Crm.OBA.OpenBankingAPIAccess.Program.CreateCRMImportRecord(String jsonString) in C:\Working\Program.cs:line 332


System.InvalidOperationException: Identity of caller can not be found in HttpContext.
   at Microsoft.Xrm.Kernel.Runtime.UserIdValidator.Validate(Guid userId, Boolean isInClientContext) +0x26
   at Microsoft.Crm.Extensibility.PipelineExecutionContext.get_InitiatingUserId() +0x2b
   at Microsoft.Crm.ObjectModel.CallbackRegistationExpanderPlugin.<>c__DisplayClass6_0.<Execute>b__0() +0x16c
   at Microsoft.PowerApps.CoreFramework.ActivityLoggerExtensions.Execute(ILogger logger, EventId eventId, ActivityType activityType, Action action, IEnumerable`1 additionalCustomProperties) +0x90
   at Microsoft.Xrm.Telemetry.XrmTelemetryExtensions.Execute(ILogger logger, XrmTelemetryActivityType activityType, Action action) +0x13
   at Microsoft.Crm.Extensibility.V5PluginProxyStep.ExecuteInternal(PipelineExecutionContext context) +0x0
   at Microsoft.Crm.Extensibility.VersionedPluginProxyStepBase.Execute(PipelineExecutionContext context) +0x3b: Microsoft Dynamics CRM has experienced an error. Reference number for administrators or support: #B92E6EBA

**Comment by MattB-msft** [comment] 2021-07-27 22:30
@krishire 
The team working on the SDK Client is not able to reproduce this situation,  its been tested with WS-TRUST ( office 365 ) and with JWT ( service accounts and user accounts ) 
We are testing this against an environment in NorthAmerica.   

is this still occurring for you?

**Comment by krishire** [comment] 2021-07-28 00:10
Hi Matt,
Thanks for looking into this issue, just now the engineering team is able
to simulate this issue, what they found is I have a power Automate flow
that gets triggered on the update of the entity record where the file gets
uploaded and committed and that flow is somehow causing this issue, they
asked me to turn off the flow and try out and issue is not happening, but
the flow is very important one I cannot leave it turned off, so I have
asked what is the connection here, since the flow triggers on one of the
"Ready to process" status of the record where the file gets uploaded and
processes the file to import data into crm. Waiting for their reply.

I will update once I receive further feedback from them.

Thanks,
Krish.

**Comment by MattB-msft** [comment] 2021-07-28 00:37
Got it. Ok, that makes sense.  and now that I look at the stack trace I see at Microsoft.Crm.ObjectModel.CallbackRegistationExpanderPlugin.<>c__DisplayClass6_0.b__0() +0x16c
which is indicating that there is a flow attached. 

Going to close this bug here as its not related to the service client itself.

**Closed by MattB-msft** 2021-07-28 00:37 UTC
Labels: Investigating

**Comment by krishire** [comment] 2021-07-28 06:26
Yes Matt, I think if I introduce sone delays within the flow as first step,
this issue may get fixed, going to try it first thing after I login to
office today. Waiting for some suggestion from the engineering team as
well.
