### ISSUE TITLE
REST calls have empty Bearer token in the newest version (0.4.21)

### ISSUE THREAD

**Issue by pareszka** [microsoft/PowerPlatform-DataverseServiceClient#162] opened 2021-09-08 13:27 UTC
I upgraded Dataverse.Client and some of my tests started to fail. Retrieving records still work, as it's going through SOAP, but creating a new one fails. The exceptions is just: 
`JsonReaderException: Error reading JObject from JsonReader. Path '', line 0, position 0.`

I checked with Fiddler what exactly is going on. I called CreateAsync for a contact, I can see successful calls for RetrieveCurrentOrganizaton, WhoAmI and for retrieving EntityMetadata, but then there is a POST to /api/data/v9.2/contacts, which is getting status 401.
I checked requests headers and this is how Authorization header looks like: 
![image](https://user-images.githubusercontent.com/81615171/132517461-3250f8e9-aaeb-4c1b-b322-c5d1649181c5.png)

I compared the call from my app with older version of Dataverse.Client (0.4.19), and it looks normally there:
![image](https://user-images.githubusercontent.com/81615171/132517590-17e5dad2-6c7e-4759-a7d6-19505607502c.png)

I also noticed that Cookies section is empty for new version, when for old version it looks like that:
![image](https://user-images.githubusercontent.com/81615171/132517825-9ae0e80d-88fb-4fe2-a632-55751a256e8d.png)

**Comment by MattB-msft** [comment] 2021-09-10 01:31
Could you give us a bit more info on what your code does for authentication and use case? 

Also is this happening immediately? Or after some time ? 

Thanks

**Comment by Rtalos** [comment] 2021-09-13 14:06
We are getting this same error.


![image](https://user-images.githubusercontent.com/19684631/133092019-b2988d92-7035-4704-a45c-681745a39e40.png)

![image](https://user-images.githubusercontent.com/19684631/133092071-058c0d7d-d098-474a-95b7-bdd0d3cf5f7c.png)


This seems to be happening to us when we try to update/delete SalesOrder. 

We used this guide with our ops to set up the auth: https://docs.microsoft.com/en-us/powerapps/developer/data-platform/use-single-tenant-server-server-authentication

We use this to retrieve the token

![image](https://user-images.githubusercontent.com/19684631/133097774-eca1bd38-6ad7-4395-866b-ae7062d5f9cf.png)

![image](https://user-images.githubusercontent.com/19684631/133097785-db6adcc1-5c18-49e9-8fe0-9dd06791f952.png)


![image](https://user-images.githubusercontent.com/19684631/133094381-41e6dfb8-ee06-4ca7-83a0-2dc22694d027.png)


This is the the code where the call fails:

![image](https://user-images.githubusercontent.com/19684631/133098208-fb570731-f8f5-40a7-98ef-52edf48c63ff.png)

**Comment by MattB-msft** [comment] 2021-09-13 17:13
@Rtalos , thanks for adding info.. 

I am seeing the following: 
Your managing the token on your own, passing in a handler to the constructor,  whenever the client needs the token its going to call "GetToken",  which I assume you have code to manage that. ( You didn't include that, just GetAzureToken which does not seem to be called anywhere ) .  I am going to guess your using the memory cache to be your token cache.

Your then creating a clone and passing that to RemoveSalesOrders via DI, 
In there, your setting up a Service Context, and using a linq operation to execute an update,  ( in this case a delete ),  and the token is not being appended to the WebAPI calls,  it IS there on the OrganziationService calls. 

is that accurate? 

what version of .net are you using and what host platform? ( windows / non windows?)

**Comment by Rtalos** [comment] 2021-09-14 09:00
@MattB-msft , thank your for the response!

Yes, your assumptions are correct (sorry I missed adding the in-memory method), there is an in-memory cache between GetAzureToken method and GetToken inside the token provider function. It looks like this, I have also tried bypassing this but it is still the same error:

![image](https://user-images.githubusercontent.com/19684631/133222359-11934425-1538-4d93-bb50-9ffd859bece5.png)

To answer your question.

>What version of .net are you using and what host platform? ( windows / non windows?)

We use **netcore 3.1** and I am currently developing this project on my local computer on **Windows 10 OS**.

>Also can you confirm that your code "GetToken" is returning tokens all the time?

From what I can see, yes. I did also bypass the in-memory logic and it still produces the same error.


To add a bit more information. I did some more testing today and the first thing I wanted to try was to go back to the 0.4.20 version. I only downgraded the **Microsoft.PowerPlatform.Dataverse.Client** package, like so:

![image](https://user-images.githubusercontent.com/19684631/133224035-803fef68-30ab-4100-ab49-0a2573fc9d45.png)

This seems to work. Looking through fiddler and this is what I see:

![image](https://user-images.githubusercontent.com/19684631/133225825-02c9acfb-839a-4c8f-8f03-0b45396adfdb.png)

I then went back to 0.4.21:

![image](https://user-images.githubusercontent.com/19684631/133225904-30cb3767-eda6-47fd-8fa7-3db07afa4be4.png)

And again it's producing the error. I have tried multiple different entities and they all give 401:

![image](https://user-images.githubusercontent.com/19684631/133225946-d2e45a11-81ae-40dd-a6f4-9364ebb0554c.png)

What is interesting is that it seems to only be when saving changes. If I do a simple select it still works and it is the correct product that is being returned:

![image](https://user-images.githubusercontent.com/19684631/133226567-65375758-6035-4d5f-a4b9-95e808bafe6f.png)

![image](https://user-images.githubusercontent.com/19684631/133227148-d2759b09-8fd9-431d-ad28-0df5e3ee32a3.png)

**Comment by MattB-msft** [comment] 2021-09-25 00:22
@Rtalos  Your issue should now be fixed,  Can you retest please with the 0.5.2 package., 
@pareszka Could you please retest now with 0.5.2 package please.

**Comment by Rtalos** [comment] 2021-09-29 12:18
@MattB-msft 

Sadly the issue seems to persist for us. Source code is unchanged from last post.

 
![image](https://user-images.githubusercontent.com/19684631/135266568-f4437797-44fc-42e7-bdbc-12097198344a.png)
![image](https://user-images.githubusercontent.com/19684631/135266589-8b0eee7d-d836-41e6-a7fa-3c8516ecfeff.png)
![image](https://user-images.githubusercontent.com/19684631/135266606-7d5b6683-1001-4e92-83cc-ceaeeb187301.png)

ServiceClient LastError:
![image](https://user-images.githubusercontent.com/19684631/135266634-b6432d3a-0902-4216-977a-7eea1f6cd015.png)

**Comment by MattB-msft** [comment] 2021-09-29 12:30
@Rtalos can you share a 'working' repro of your issue with us? As well as a verbose log from you client showing the failure? 

If you can create a temp private repro on git, you can share it directly with me for us to look at. 

We thought we had you issue identified and fixed but we're not 100% sure which is wet we didn't close the issue. 

Thanks

**Comment by Rtalos** [comment] 2021-09-29 12:39
@MattB-msft ok, Ill see what I can do with the repro.

For now I found this aswell in same controller switching between 0.4.20 and 0.5.2 on the injected ServiceClient. Don't know if it helps.

![image](https://user-images.githubusercontent.com/19684631/135269610-9b8b5512-58b1-45dc-9ccb-128702cc0198.png)

**Comment by Rtalos** [comment] 2021-09-30 08:25
@MattB-msft 

I managed to get a repro working, this produces the exact same behaviour as our main app.

https://github.com/Rtalos/ServiceClientReproIssue162

I don't know how useful this will be because I am limited in what I can share (even privately). If you really need the information below to be able to solve this issue I can try to talk to management again and see what we can do:

- I am not allowed to disclose
  - Dynamics URL
  - Azure Tenant ID
  - Azure Client Secret
  - Azure Client ID

**Comment by MattB-msft** [comment] 2021-10-01 17:31
@Rtalos  Confirmed bug.. we are working though understanding why this is happening in this case.

**Comment by MattB-msft** [comment] 2021-10-01 18:59
@Rtalos 
As an update the engineer looking at it has it fixed,  we need to correct one other issue and we will publish an update either later today or tomorrow with the fix.

**Closed** 2021-10-04 20:33 UTC
Labels: bug
