### ISSUE TITLE
RequestId is not send via the web api

### ISSUE THREAD

**Issue by meghuizen** [microsoft/PowerPlatform-DataverseServiceClient#209] opened 2021-12-01 12:01 UTC
I want to add a request id, which I can pickup in the plugins to do business logic on.
This is logic I already had when using the old API client.

Example Code
```csharp
CreateResponse crResp = (CreateResponse)myServiceClient.Execute(new CreateRequest
                        {
                            Target = myEntity,
                            RequestId = MySharedGuidWithAPlugin
                        });
```

In my plugin code I'm using
```csharp
((IExecutionContext)serviceProvider.GetService(typeof(IPluginExecutionContext))).RequestId
```

However I'm not able to pick that up in the plugin.
Is this something which still needs to be integrated?

**Comment by MattB-msft** [comment] 2021-12-01 16:34
Request ID's are set via the WebAPI request's and you can see them via a fiddler trace. 
You can cross check the behavior by setting UseWebAPI = false on the client before you send your request. 

Adding @JimDaly for comment here as well.

**Comment by JimDaly** [comment] 2021-12-01 17:12
If your purpose is to have some information in your plug-in, you can use the `tag` to add a value which will be available as a shared variable in your plug-in. See [Add a Shared Variable from the Web API](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/webapi/compose-http-requests-handle-errors#add-a-shared-variable-from-the-web-api)

Since this question is related to DataverseServiceClient and is using IOrganizationService interface, I expect the actual style in which you would pass it would be like this [Add a shared variable from the Organization Service](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/org-service/use-messages#add-a-shared-variable-from-the-organization-service)

**Comment by meghuizen** [comment] 2021-12-01 18:28
Thanks @JimDaly for the extra explanation regarding that. Will take that into account and maybe change that. Currently we use the RequestID as "legacy" from when a plugin triggers an action on another entity, where in the other plugin needs a different execution path because of that.

@MattB-msft Thanks for your comment. I might try to attach Fiddler to it tomorrow, however I did cross check it by explicitely using UseWebAPI on false and that fixed my issue. 
I will however double check this tomorrow to know for certain I didn't miss anything.

**Comment by MattB-msft** [comment] 2021-12-08 16:36
As a follow up, we confirmed that the Request ID is being passed via the webAPI leg, and we are researching the server side disconnect there. 

If you want to continue to use RequestID for now, and do now want to switch to Tag,  Please continue to set UseWebAPI to false until we get it patched server side.

**Comment by MattB-msft** [comment] 2023-07-20 17:55
Cleaning up this issue, 
This was resolved in the last year.. this was missed for cleanup.

**Closed by MattB-msft** 2023-07-20 17:55 UTC
Labels: Server Platform API Fix\Change
