### ISSUE TITLE
Missing cancellation token in external authentication function

### ISSUE THREAD

**Issue by svejdo1** [microsoft/PowerPlatform-DataverseServiceClient#165] opened 2021-09-20 08:13 UTC
The function for getting auth token from external source `Func<string, Task<string>> tokenProviderFunction` is lacking specification of cancellation token; I'd expect this semantic to be actually `Func<string, CancellationToken, Task<string>> tokenProviderFunction`  instead.

The problem is a) I have to come up with some arbitry timeout on my side b) if cds request is cancelled still we have to wait till the request for getting token is finished.

**Comment by MattB-msft** [comment] 2021-09-20 16:34
@svejdo1 , use of the Token provider function acts as an offload behavior for managing tokens. 
There is no higher process that will terminate that request, and that request is made when the process is attempting to access one of the internal API endpoints.  Its up to the token method itself to trigger the abort and raise an exception. 

We chose not to include a cancelation token in that method call to make it a simpler syntax to use, and as for those methods that support cancelation, it would be triggered on return from the function itself. 

regarding your concerns.. 
a-  yes.. This is intentional.  This will be entirely up to how your building, updating, caching and returning your token.  in this mode, the client makes no demands on how the called code gets to the access token,  only that it does get it.  The dataverse client can do this on its own and has an internal set of patterns for this. 

b- the client request to dataverse, if canceled, and using one of the API patterns that supports it internally, would trip the cancel on return from the token call, once the client regains control of the flow. 

Is there a specific scenario that has raised this concern?

**Comment by svejdo1** [comment] 2021-09-20 21:00
@MattB-msft  - generally speaking not respecting cancellation token is making DDOS attacks easy / cheaper as client can simply put a lot of requests on service and hang up (I mean you should be having throttling limits before this, just commenting on general pattern). What raised this concern was scenario where UI action called our service endpoint which was doing a lot of CDS calls within the same web request, the web request was supposed to be cancelled to return stuff to UI quickly, but we're still block-waiting on getting the token - making the perceived response very slow.

**Comment by MattB-msft** [comment] 2021-09-20 22:20
Interesting, so in your case, it seems like it would not have really mattered unless you were checking between the token requests as MSAL does not accept a cancelation token directly.  
Your code would have to have checked the status of the cancelation token between retries, and your looking to use the upstream cancelation tokens to short circuit your retry mechanic.  Is that really what your looking for there? 

As I said, We do respect cancelation tokens for the internal API endpoints that support them,  We also have throttles and API limits to protect the service.

**Comment by MattB-msft** [comment] 2021-10-04 20:39
Closing this as by design for now.

**Closed by MattB-msft** 2021-10-04 20:39 UTC
